70 support for rsm plots
FAIRmat-NFDI/nomad-measurements pull request #78
Opened 2024-02-12 12:59 UTC by ka-sarthak

2024-03-12 14:48 UTC, hampusnasstrom requested changes
Good job! Just fix the q_norm thing.

2024-03-12 14:48 UTC, hampusnasstrom commented on src/nomad_measurements/xrd/schema.py
> +        type=np.dtype(np.float64), shape=['*'],
If you do this, there is no need for `derive_n_values()`, `n_values`, or `n_values_arr` (can be removed)

2024-03-12 14:48 UTC, hampusnasstrom commented on src/nomad_measurements/xrd/schema.py
> -            'x': 'q_vector', 'y': 'intensity'
Keep here and rename to `q_norm`

2024-03-12 14:48 UTC, hampusnasstrom commented on src/nomad_measurements/xrd/schema.py
> +    # results.section_def = XRDResult
Put this back

2024-03-12 14:48 UTC, hampusnasstrom commented on src/nomad_measurements/xrd/schema.py
> +                    # q_vector=result.q_vector,
Put this back

2024-03-12 15:47 UTC, ka-sarthak commented on src/nomad_measurements/xrd/IKZ.py
> +        # imgdata = np.array(imgdata)
Deleting the commented out code

2024-03-12 16:33 UTC, ka-sarthak commented on src/nomad_measurements/xrd/schema.py
> +    )
Yes, this is not required

2024-03-13 17:41 UTC, hampusnasstrom approved these changes
I tested it now and everything works. I have some suggestions on the plots but I will write a separate issue for this. For now I will go ahead and merge this.

2024-03-13 17:41 UTC, merged